- name: Ensure Python3 and virtualenv are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-venv

- name: Create application directory
  file:
    path: "{{ app_deploy_location }}"
    state: directory

- name: Create virtual environment
  command: python3 -m venv {{ app_deploy_location }}/venv
  args:
    creates: "{{ app_deploy_location }}/venv/bin/activate"

- name: Copy the application wheel file
  copy:
    src: "files/application/{{ app_wheel_file }}"
    dest: "{{ app_deploy_location }}/{{ app_wheel_file }}"

- name: Install the wheel file
  pip:
    name: "{{ app_deploy_location }}/{{ app_wheel_file }}"
    virtualenv: "{{ app_deploy_location }}/venv"

- name: Create systemd service file for the application
  template:
    src: templates/example_app.service.j2
    dest: /etc/systemd/system/example_app.service
  notify:
    - restart example app

- name: Ensure the application is running
  systemd:
    name: example_app
    state: started
    enabled: yes

