- name: Configure CA Certificates and Deploy Application
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - include_tasks: tasks/ca_certificates.yml
    - include_tasks: tasks/custom_ca_certificates.yml
    - include_tasks: tasks/deploy_application.yml

